backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "widgets"
    label: "Components"
    files:
    - file: "src/md-store/apply-widget.md"
      label: "Application Widget"
      name: "apply-widget"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "apply-widget"}
        - {label: "Apply Message", name: apply_message, widget: string}
        - {label: Application Types, name: apply_types, widget: list, fields: [
            {label: Heading, name: heading, widget: string},
            {label: Description, name: description, widget: markdown},
            {label: "Application open?", name: open, widget: select, default: "closed", options: [
              {label: "Yes", value: "open"},
              {label: "No", value: "closed"}
            ]},
            {label: "Infosession Information (Date/Time and Location)", name: infosession, widget: markdown},
            {label: "Application Due Date", name: apply_deadline, widget: date},
            {label: "Linked Learn More Page", name: linked_page, widget: relation, collection: pages, searchFields: [label, name], valueField: name},
            {label: "Application Link", name: apply_link, widget: string}
        ]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/md-store/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
          - {label: "Path", name: path, widget: "hidden", default: "/"}
          - {label: "Title", name: title, widget: "string"}
          - {label: "Body", name: body, widget: "markdown"}
      - file: "src/md-store/club.md"
        label: "Club Page"
        name: "club"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "club"}
          - {label: "Path", name: path, widget: "hidden", default: "/club"}
          - {label: "Title", name: title, widget: "string"}
          - {label: "Body", name: body, widget: "markdown"}
      - file: "src/md-store/about.md"
        label: "Team Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Path", name: path, widget: "hidden", default: "/about"}
          - {label: "Title", name: title, widget: "string"}
          - {label: "Body", name: body, widget: "markdown"}
          - {label: "Officers", name: officers, widget: list, fields: [
            {label: "Name", name: name, widget: string},
            {label: "Primary Role", name: role, widget: string},
            {label: "Secondary Role", name: secondary_role, widget: string, required: false},
            {label: "Profile Picture", name: profile_picture, widget: image}
          ]}
      - file: "src/md-store/decal.md"
        label: "DeCals"
        name: "decals"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "decals"}
          - {label: "Path", name: path, widget: "hidden", default: "/decals"}
          - {label: "DeCals", name: courses, widget: list, fields: [
            {label: "DeCal Title", name: title, widget: string},
            {label: "DeCal Description", name: description, widget: markdown},
            {label: "Lessons", name: lessons, widget: list, fields: [
            ]}
          ]}


