const officerContent = [
{
name: "Sahil Sanghvi",
	position: "President",
    phrase: "Enjoys looking at well-made maps",
    img: "/img/about/officers-sp21/sahil.png",
},
{
name: "Renee Utter",
	position: "President",
    phrase: "enjoys hellen keller conspiracy theories",
    img: "/img/about/officers-sp21/renee.png",
},
{
name: "Annie Lin",
	position: "VP Services, Web Team Lead",
    phrase: "did u know ice cream has more carbs than pasta? <3",
    img: "/img/about/officers-sp21/annie.png",
},
{
name: "Jenny Chen",
    position: "VP Education Outreach, Gold Team Lead",
    phrase: "clam chowder is seafood boba",
    img: "/img/about/officers-sp21/jenny.png",
},
{
name: "Lindsey Guan",
    position: "VP Education Coordinator, Gold Photo Lead",
    phrase: "let's talk mason jars",
    img: "/img/about/officers-sp21/lindsey.png",
},
{
name: "Farhan Hossain",
    position: "VP External, Blue Team Lead",
    phrase: "i hate trader joe's takis",
    img: "/img/about/officers-sp21/farhan.png",
},
{
name: "Kelly Ma",
    position: "VP Internal, Gold Team Lead",
    phrase: "needs naps and boba for life",
    img: "/img/about/officers-sp21/kelly.png",
},
{
name: "Vivian Zhang",
    position: "Marketing Team Lead",
    phrase: "holding u soft & gently in the astral plane :,)",
    img: "/img/about/officers-sp21/vivian.png",
},
{
name: "Jihyun Kim",
    position: "Marketing Team Lead",
    phrase: "hot cheetos >> cheetos",
    img: "/img/about/officers-sp21/jihyun.png",
},
{
name: "Albert Tian",
	position: "VP Tech",
    phrase: "1 2 mayweather",
    img: "/img/about/officers-sp21/albert.png",
},
{
name: "Elly Lee",
    position: "VP Finance",
    phrase: "jafeel me?",
    img: "/img/about/officers-sp21/elly.png",
},
{
name: "Elizabeth Tang",
position: "Photo Decal Facilitator",
phrase: "i like big crocs and i cannot lie",
img: "/img/about/officers-sp21/tang.png",
},
{
name: "Emily Shaw",
    position: "Intro DeCal Facilitator",
    phrase: "spirit animal is an egg",
    img: "/img/about/officers-sp21/emily.png",
},
{
name: "Gloria Fung",
    position: "Intro DeCal Facilitator",
    phrase: "latte art amateur",
    img: "/img/about/officers-sp21/gloria.png",
},
{
name: "Ryan Yu",
    position: "Intro DeCal Facilitator, Gold Team Lead",
    phrase: "my name ryan yu",
    img: "/img/about/officers-sp21/ryan.png",
},
{
name: "Sophie Doucet",
    position: "Intro DeCal Facilitator",
    phrase: "I have a cat for each of my hands",
    img: "img/about/officers-sp21/sophie.png",
},
{
name: "Tucker Beachem",
	position: "Gold Team Lead",
    phrase: "in my room",
    img: "/img/about/officers-sp21/tucker.png",
},
{
name: "Jason Cao",
	position: "VP Internal, Gold Photo Lead",
    phrase: "The Chesapeake Bay is the best bay,",
    img: "/img/about/officers-sp21/jason.png",
},
{
name: "Danny Ha",
	position: "Senior Advisor",
    phrase: "reminder to drink some water",
    img: "/img/about/officers-sp21/danny.png",
},
{
name: "Megan Chai",
	position: "Blue Team Lead",
    phrase: "i <3 trader joe's takis",
    img: "/img/about/officers-sp21/megan.png",
},
{
name: "Joshua Yao",
	position: "Senior Advisor",
    phrase: "baja'd his last blast",
    img: "img/about/officers-sp21/josh.png",
},
]

export {officerContent}